CREATE TABLE IF NOT EXISTS Person
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(400) NOT NULL,
    surname     varchar(400) NOT NULL,
    patronymic  varchar(400),
    age         int,
    gender      varchar(10),
    nationality varchar(100)
)

