// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPerson struct {
	Name        string `json:"Name"`
	Surname     string `json:"Surname"`
	Patronymic  string `json:"Patronymic"`
	Age         int    `json:"Age"`
	Nationality string `json:"Nationality"`
	Gender      string `json:"Gender"`
}

type Person struct {
	ID          string `json:"ID"`
	Name        string `json:"Name"`
	Surname     string `json:"Surname"`
	Patronymic  string `json:"Patronymic"`
	Age         int    `json:"Age"`
	Nationality string `json:"Nationality"`
	Gender      string `json:"Gender"`
}

type PersonInput struct {
	ID          string `json:"ID"`
	Name        string `json:"Name"`
	Surname     string `json:"Surname"`
	Patronymic  string `json:"Patronymic"`
	Age         int    `json:"Age"`
	Nationality string `json:"Nationality"`
	Gender      string `json:"Gender"`
}

type PersonMutationPayload struct {
	Ok bool `json:"ok"`
}
